apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-data
  namespace: radicale
  labels:
    app: radicale-data
spec:
  storageClassName: retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale-config
  namespace: radicale
  labels:
    app: radicale-config
spec:
  storageClassName: retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi