apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: radicale-middleware
  namespace: radicale
spec:
  forwardAuth:
    address: http://radicale-auth.radicale.svc.cluster.local:4181
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User