apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: radicale-proxy
  namespace: radicale
spec:
  chart: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  targetNamespace: radicale
  valuesContent: |-
    config:
      existingSecret: radicale-secret
      configFile: |-
        email_domains = [ "*" ]
        upstreams = [ "static://200" ]
        reverse_proxy = true
        set_xauthrequest = true
        provider = oidc
        cookie_secure = true
        redirect_url = https://cal.ryzen.me
        oidc_issuer_url = https://auth.ryzen.me/realms/public
        code_challenge_method = S256